apiVersion: v1
kind: Service
metadata:
  name: project-2-service
spec:
  type: NodePort
  selector:
    app: project-2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30008  # Choose a valid port between 30000â€“32767

